title: 이충섭
name: 이충섭
email: csmugene@gmail.com
description: Software Engineer

baseurl: "/blog"
url: ""

display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: "스마트택배"
project_one_description: 누적 다운로드수 580만, 실제 사용자 300만명이 사용하는 어플리케이션으로 성장
project_one_url: https://github.com/jameshamann/jekyll-material-theme
project_one_icon: location_on

project_two: C Alarm
project_two_description: 설정한 알람 시간에 가상화폐의 가격을 보여주는 어플리케이션
project_two_url: https://github.com/jameshamann/jekyll-material-theme
project_two_icon: photo_camera


project_three: 퀵커
project_three_description: 퀵 서비스 업체 50여개에서 사용 중
project_three_url: https://github.com/jameshamann/jekyll-material-theme
project_three_icon: hotel


project_four: 메이크샵 모바일 SDK
project_four_description: Describe your project!
project_four_url: https://github.com/jameshamann/jekyll-material-theme
project_four_icon: restaurant

project_five: Android DRM SDK
project_five_description: Describe your project!
project_five_url: https://github.com/jameshamann/jekyll-material-theme
project_five_icon: restaurant

project_six: Flash HLS DRM SDK
project_six_description: Describe your project!
project_six_url: https://github.com/jameshamann/jekyll-material-theme
project_six_icon: restaurant


portfolio_heading: Portfolio
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: android
  - name: bitbucket
  - name: c
  - name: cplusplus
  - name: csharp
  - name: git
  - name: github
  - name: gradle
  - name: java
  - name: javascript
  - name: mysql
  - name: php
  - name: slack
  - name: sourcetree
  - name: visualstudio

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Check it out

#github: https://github.com/jameshamann/jekyll-material-theme
#medium: https://medium.com

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: https://csmugene.github.io/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
