# Site settings
title: Hanuman
description: Hanuman is a minimal yet powerful Jekyll theme for your blogs and websites.
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: / # the subpath of your site, e.g. /blog/ or / for root
url: "https://csmugene.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
portfolio: portfolio
post: post
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: csmugene #github username
repo: csmugene.github.io #github repository
branch: master #branch
relative_source: ../ #source directory
destination: ..-pages/ #destination directory
production_url:  https://csmugene.github.io/
source_url:  https://github.com/csmugene/csmugene.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml